import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import './globals.css';
import NextAuthProvider from '@/providers/next-auth.provider';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import ReduxProvider from '@/providers/redux.provider';
// import TanstackProvider from '@/providers/tanstack.provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={(cn(inter.className), 'bg-gray-100')}>
        <NextAuthProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
